# Generated by Django 4.1.4 on 2022-12-20 16:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155, verbose_name='Key of property')),
                ('value', models.CharField(max_length=155, verbose_name='Value of property')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Too small value'), django.core.validators.MaxValueValidator(9999, 'Too big value ')], verbose_name='Value of object')),
                ('modified_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='entity', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('properties', models.ManyToManyField(blank=True, related_name='properties', to='service.property', verbose_name='Properties of object')),
            ],
        ),
    ]
